// Technical Skills
import type { Skill, SkillGroup } from './types';

export const technicalSkills: Skill[] = [
  // Frontend Technologies
  {
    name: 'React',
    category: 'frontend',
    proficiency: 'expert',
    yearsOfExperience: 4,
    description: 'Building modern, interactive user interfaces with hooks, context, and state management',
    projects: ['react-portfolio', 'vue-dashboard'],
    lastUsed: '2024-12',
  },
  {
    name: 'Vue.js',
    category: 'frontend',
    proficiency: 'expert',
    yearsOfExperience: 5,
    description: 'Component-based architecture with Vuex, Vue Router, and Composition API',
    projects: ['vv-vehicle-management', 'vue-dashboard'],
    lastUsed: '2024-11',
  },
  {
    name: 'TypeScript',
    category: 'frontend',
    proficiency: 'expert',
    yearsOfExperience: 3,
    description: 'Type-safe JavaScript development with advanced type features',
    projects: ['react-portfolio', 'ionic-healthcare-app'],
    lastUsed: '2024-12',
  },
  {
    name: 'Angular',
    category: 'frontend',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'Enterprise-scale applications with RxJS and Angular Material',
    projects: ['ionic-healthcare-app'],
    lastUsed: '2023-04',
  },
  {
    name: 'Three.js',
    category: 'frontend',
    proficiency: 'advanced',
    yearsOfExperience: 2,
    description: '3D graphics and WebGL for interactive visualizations',
    projects: ['react-portfolio'],
    lastUsed: '2024-12',
  },

  // Backend Technologies
  {
    name: 'Laravel',
    category: 'backend',
    proficiency: 'expert',
    yearsOfExperience: 5,
    description: 'PHP framework with Eloquent ORM, Blade templating, and Artisan CLI',
    projects: ['vv-vehicle-management'],
    lastUsed: '2024-10',
  },
  {
    name: 'Node.js',
    category: 'backend',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'Server-side JavaScript with Express.js and real-time applications',
    projects: ['vue-dashboard'],
    lastUsed: '2022-12',
  },
  {
    name: 'PHP',
    category: 'backend',
    proficiency: 'expert',
    yearsOfExperience: 6,
    description: 'Server-side scripting with OOP principles and modern PHP features',
    projects: ['vv-vehicle-management'],
    lastUsed: '2024-10',
  },

  // Mobile Development
  {
    name: 'Flutter',
    category: 'mobile',
    proficiency: 'expert',
    yearsOfExperience: 3,
    description: 'Cross-platform mobile development with Dart and Material Design',
    projects: ['flutter-mobile-app'],
    lastUsed: '2023-10',
  },
  {
    name: 'Ionic',
    category: 'mobile',
    proficiency: 'expert',
    yearsOfExperience: 4,
    description: 'Hybrid mobile development with Angular and Cordova plugins',
    projects: ['ionic-hybrid-app'],
    lastUsed: '2023-04',
  },
  {
    name: 'Dart',
    category: 'mobile',
    proficiency: 'expert',
    yearsOfExperience: 3,
    description: 'Programming language for Flutter development',
    projects: ['flutter-mobile-app'],
    lastUsed: '2023-10',
  },

  // Databases
  {
    name: 'MySQL',
    category: 'database',
    proficiency: 'expert',
    yearsOfExperience: 5,
    description: 'Relational database design, optimization, and complex queries',
    projects: ['vv-vehicle-management'],
    lastUsed: '2024-10',
  },
  {
    name: 'PostgreSQL',
    category: 'database',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'Advanced SQL features, JSON support, and performance tuning',
    projects: ['ionic-healthcare-app'],
    lastUsed: '2023-04',
  },
  {
    name: 'MongoDB',
    category: 'database',
    proficiency: 'intermediate',
    yearsOfExperience: 2,
    description: 'NoSQL document database with aggregation pipelines',
    projects: ['vue-dashboard'],
    lastUsed: '2022-12',
  },
  {
    name: 'Redis',
    category: 'database',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'In-memory data structure store for caching and sessions',
    projects: ['vv-vehicle-management'],
    lastUsed: '2024-10',
  },

  // DevOps & Cloud
  {
    name: 'Docker',
    category: 'devops',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'Containerization and orchestration with Docker Compose',
    projects: ['vv-vehicle-management'],
    lastUsed: '2024-10',
  },
  {
    name: 'Git',
    category: 'devops',
    proficiency: 'expert',
    yearsOfExperience: 6,
    description: 'Version control with branching strategies and CI/CD',
    projects: ['react-portfolio', 'vv-vehicle-management', 'flutter-mobile-app'],
    lastUsed: '2024-12',
  },
  {
    name: 'AWS',
    category: 'cloud',
    proficiency: 'intermediate',
    yearsOfExperience: 2,
    description: 'Cloud services including EC2, S3, and RDS',
    projects: ['vue-dashboard'],
    lastUsed: '2022-12',
  },
  {
    name: 'Firebase',
    category: 'cloud',
    proficiency: 'advanced',
    yearsOfExperience: 3,
    description: 'Backend-as-a-Service with authentication and real-time database',
    projects: ['flutter-mobile-app'],
    lastUsed: '2023-10',
  },

  // Programming Languages
  {
    name: 'JavaScript',
    category: 'languages',
    proficiency: 'expert',
    yearsOfExperience: 6,
    description: 'Modern ES6+ features, async programming, and DOM manipulation',
    projects: ['react-portfolio', 'vue-dashboard'],
    lastUsed: '2024-12',
  },
  {
    name: 'Python',
    category: 'languages',
    proficiency: 'intermediate',
    yearsOfExperience: 2,
    description: 'Data analysis and automation scripts',
    projects: [],
    lastUsed: '2023-06',
  },
  {
    name: 'Java',
    category: 'languages',
    proficiency: 'intermediate',
    yearsOfExperience: 2,
    description: 'Object-oriented programming and Spring framework',
    projects: [],
    lastUsed: '2022-08',
  },
];

export const skillGroups: SkillGroup[] = [
  {
    category: 'frontend',
    title: 'Frontend Development',
    description: 'Modern web technologies for creating interactive user interfaces',
    skills: technicalSkills.filter(skill => skill.category === 'frontend'),
  },
  {
    category: 'backend',
    title: 'Backend Development',
    description: 'Server-side technologies and API development',
    skills: technicalSkills.filter(skill => skill.category === 'backend'),
  },
  {
    category: 'mobile',
    title: 'Mobile Development',
    description: 'Cross-platform and hybrid mobile application development',
    skills: technicalSkills.filter(skill => skill.category === 'mobile'),
  },
  {
    category: 'database',
    title: 'Database Management',
    description: 'Database design, optimization, and management',
    skills: technicalSkills.filter(skill => skill.category === 'database'),
  },
  {
    category: 'devops',
    title: 'DevOps & Cloud',
    description: 'Deployment, containerization, and cloud services',
    skills: technicalSkills.filter(skill => skill.category === 'devops' || skill.category === 'cloud'),
  },
  {
    category: 'languages',
    title: 'Programming Languages',
    description: 'Core programming languages and frameworks',
    skills: technicalSkills.filter(skill => skill.category === 'languages'),
  },
];
