// Web Development Projects
import type { Project } from './types';
import { PROJECT_IDS } from './types';

export const webProjects: Project[] = [
  {
    id: PROJECT_IDS.VV_VEHICLE_MANAGEMENT,
    title: 'VV Vehicle Management System',
    description: 'Comprehensive fleet management solution with real-time tracking, maintenance scheduling, and driver analytics.',
    shortDescription: 'Fleet management system with real-time tracking and analytics',
    longDescription: 'A full-stack vehicle management system built for a logistics company. Features include real-time GPS tracking, maintenance scheduling, driver performance analytics, fuel consumption monitoring, and comprehensive reporting. The system handles 500+ vehicles and processes thousands of data points daily.',
    technologies: [
      { name: 'Vue.js', category: 'frontend', proficiency: 'expert' },
      { name: 'Laravel', category: 'backend', proficiency: 'expert' },
      { name: 'MySQL', category: 'database', proficiency: 'advanced' },
      { name: 'Redis', category: 'database', proficiency: 'intermediate' },
      { name: 'Docker', category: 'devops', proficiency: 'advanced' },
      { name: 'WebSocket', category: 'other', proficiency: 'advanced' },
    ],
    category: 'web',
    status: 'completed',
    featured: true,
    images: {
      thumbnail: '/asset/projects/vv-vehicle-thumb.jpg',
      hero: '/asset/projects/vv-vehicle-hero.jpg',
      screenshots: [
        '/asset/projects/vv-vehicle-1.jpg',
        '/asset/projects/vv-vehicle-2.jpg',
        '/asset/projects/vv-vehicle-3.jpg',
      ],
    },
    links: {
      live: 'https://vv-vehicles.example.com',
      github: 'https://github.com/khalil-charfi/vv-vehicle-management',
    },
    metrics: {
      users: 150,
      performance: '99.9% uptime',
      impact: '40% reduction in maintenance costs',
    },
    startDate: '2023-01',
    endDate: '2023-08',
    duration: '8 months',
    teamSize: 4,
    role: 'Lead Full-Stack Developer',
    challenges: [
      'Real-time data synchronization across multiple devices',
      'Handling large datasets with optimal performance',
      'Implementing complex business logic for fleet management',
    ],
    achievements: [
      'Reduced maintenance costs by 40% through predictive analytics',
      'Improved driver efficiency by 25% with performance tracking',
      'Achieved 99.9% system uptime with robust error handling',
    ],
  },
  {
    id: PROJECT_IDS.REACT_PORTFOLIO,
    title: 'React Portfolio Website',
    description: 'Modern, interactive portfolio website with 3D backgrounds, visitor personalization, and multi-language support.',
    shortDescription: 'Interactive portfolio with 3D effects and personalization',
    longDescription: 'A cutting-edge portfolio website showcasing my work with advanced features including 3D WebGL backgrounds, visitor personalization based on source and behavior, multi-language support (EN, FR, AR, DE), AI-powered chatbot, and comprehensive analytics. Built with performance optimization and accessibility in mind.',
    technologies: [
      { name: 'React', category: 'frontend', proficiency: 'expert' },
      { name: 'TypeScript', category: 'frontend', proficiency: 'expert' },
      { name: 'Three.js', category: 'frontend', proficiency: 'advanced' },
      { name: 'Vite', category: 'devops', proficiency: 'advanced' },
      { name: 'i18next', category: 'frontend', proficiency: 'advanced' },
      { name: 'WebAssembly', category: 'other', proficiency: 'intermediate' },
    ],
    category: 'web',
    status: 'completed',
    featured: true,
    images: {
      thumbnail: '/asset/projects/portfolio-thumb.jpg',
      hero: '/asset/projects/portfolio-hero.jpg',
      screenshots: [
        '/asset/projects/portfolio-1.jpg',
        '/asset/projects/portfolio-2.jpg',
        '/asset/projects/portfolio-3.jpg',
      ],
    },
    links: {
      live: 'https://khalilcharfi.github.io',
      github: 'https://github.com/khalil-charfi/khalilcharfi.github.io',
    },
    metrics: {
      performance: 'Lighthouse 95+',
      impact: 'Professional showcase for career opportunities',
    },
    startDate: '2024-01',
    endDate: '2024-12',
    duration: '12 months',
    teamSize: 1,
    role: 'Solo Developer',
    challenges: [
      'Optimizing 3D graphics for smooth performance',
      'Implementing complex visitor personalization logic',
      'Ensuring accessibility compliance (WCAG 2.1 AA)',
    ],
    achievements: [
      'Achieved 95+ Lighthouse performance score',
      'Implemented progressive enhancement for no-JS fallback',
      'Created reusable component library with Storybook',
    ],
  },
  {
    id: PROJECT_IDS.VUE_DASHBOARD,
    title: 'Vue.js Analytics Dashboard',
    description: 'Real-time analytics dashboard with interactive charts, data visualization, and custom reporting tools.',
    shortDescription: 'Interactive analytics dashboard with real-time data',
    longDescription: 'A comprehensive analytics dashboard built for a marketing agency. Features include real-time data visualization, interactive charts, custom report generation, user management, and data export capabilities. The dashboard processes millions of data points and provides insights for marketing campaigns.',
    technologies: [
      { name: 'Vue.js', category: 'frontend', proficiency: 'expert' },
      { name: 'Chart.js', category: 'frontend', proficiency: 'advanced' },
      { name: 'Node.js', category: 'backend', proficiency: 'advanced' },
      { name: 'MongoDB', category: 'database', proficiency: 'intermediate' },
      { name: 'Socket.io', category: 'other', proficiency: 'advanced' },
    ],
    category: 'web',
    status: 'completed',
    featured: false,
    images: {
      thumbnail: '/asset/projects/dashboard-thumb.jpg',
      hero: '/asset/projects/dashboard-hero.jpg',
      screenshots: [
        '/asset/projects/dashboard-1.jpg',
        '/asset/projects/dashboard-2.jpg',
      ],
    },
    links: {
      live: 'https://analytics-dashboard.example.com',
      github: 'https://github.com/khalil-charfi/vue-analytics-dashboard',
    },
    metrics: {
      users: 50,
      performance: 'Sub-second load times',
      impact: '50% faster report generation',
    },
    startDate: '2022-06',
    endDate: '2022-12',
    duration: '6 months',
    teamSize: 3,
    role: 'Frontend Lead',
    challenges: [
      'Handling large datasets with smooth scrolling',
      'Implementing real-time data updates',
      'Creating responsive design for various screen sizes',
    ],
    achievements: [
      'Reduced report generation time by 50%',
      'Improved user engagement with interactive charts',
      'Achieved 99.5% uptime with optimized data loading',
    ],
  },
];
