name: Bundle Size Check

on:
  pull_request:
    branches: [main, next, develop]
  push:
    branches: [main, next, develop]

jobs:
  check-bundle-size:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comparison
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Updated to LTS
          cache: 'npm'
      
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist/
            node_modules/.cache
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json', 'src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-node-
      
      - name: Install dependencies
        run: npm ci --prefer-offline
      
      - name: Build current version
        run: npm run build
      
      - name: Get current bundle size
        id: current-size
        run: |
          # Get total gzipped size more efficiently
          TOTAL_SIZE=$(find dist -name '*.js' -o -name '*.css' | xargs gzip -c | wc -c)
          TOTAL_SIZE_KB=$((TOTAL_SIZE / 1024))
          
          # Get individual chunk sizes with better formatting
          echo "📦 Current Bundle Sizes:"
          echo ""
          echo "| File | Size (gzipped) |"
          echo "|------|----------------|"
          
          # Sort by size for better readability
          find dist/assets -name '*.js' -o -name '*.css' | while read file; do
            FILENAME=$(basename "$file")
            GZIP_SIZE=$(gzip -c "$file" | wc -c)
            GZIP_SIZE_KB=$((GZIP_SIZE / 1024))
            echo "| $FILENAME | ${GZIP_SIZE_KB} KB |"
          done | sort -k3 -nr
          
          echo ""
          echo "**Total Bundle Size: ${TOTAL_SIZE_KB} KB (gzipped)**"
          echo ""
          
          # Save for comparison
          echo "size=$TOTAL_SIZE_KB" >> $GITHUB_OUTPUT
          echo "${TOTAL_SIZE_KB}" > current-size.txt
      
      - name: Check against target
        run: |
          CURRENT_SIZE=${{ steps.current-size.outputs.size }}
          TARGET_SIZE=350
          STRETCH_TARGET=300
          CRITICAL_SIZE=450
          
          echo "### 🎯 Bundle Size Report"
          echo ""
          echo "- **Current:** ${CURRENT_SIZE} KB"
          echo "- **Target:** ${TARGET_SIZE} KB"
          echo "- **Stretch Goal:** ${STRETCH_TARGET} KB"
          echo "- **Critical Limit:** ${CRITICAL_SIZE} KB"
          echo ""
          
          if [ $CURRENT_SIZE -le $STRETCH_TARGET ]; then
            echo "✅ **Excellent!** Bundle is under stretch goal!"
            echo "🏆 Savings: $((TARGET_SIZE - CURRENT_SIZE)) KB under target"
            echo "bundle_status=excellent" >> $GITHUB_OUTPUT
          elif [ $CURRENT_SIZE -le $TARGET_SIZE ]; then
            echo "✅ **Good!** Bundle meets target size!"
            echo "📊 Savings: $((TARGET_SIZE - CURRENT_SIZE)) KB under target"
            echo "bundle_status=good" >> $GITHUB_OUTPUT
          elif [ $CURRENT_SIZE -le $CRITICAL_SIZE ]; then
            echo "⚠️  **Warning:** Bundle exceeds target!"
            echo "📈 Over by: $((CURRENT_SIZE - TARGET_SIZE)) KB"
            echo "bundle_status=warning" >> $GITHUB_OUTPUT
          else
            echo "❌ **Error:** Bundle is critically large (>${CRITICAL_SIZE} KB)!"
            echo "bundle_status=error" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: Compare with base branch (PR only)
        if: github.event_name == 'pull_request'
        run: |
          # Checkout base branch
          git fetch origin ${{ github.base_ref }}
          git checkout origin/${{ github.base_ref }}
          
          # Use cached dependencies if available
          if [ -d "node_modules" ]; then
            echo "Using cached dependencies"
          else
            npm ci --prefer-offline
          fi
          
          # Build base version
          npm run build
          
          # Get base size
          BASE_SIZE=$(find dist -name '*.js' -o -name '*.css' | xargs gzip -c | wc -c)
          BASE_SIZE_KB=$((BASE_SIZE / 1024))
          
          # Checkout PR branch again
          git checkout ${{ github.head_ref }}
          
          # Compare
          CURRENT_SIZE=${{ steps.current-size.outputs.size }}
          DIFF=$((CURRENT_SIZE - BASE_SIZE_KB))
          PERCENT=$(echo "scale=1; $DIFF * 100 / $BASE_SIZE_KB" | bc -l 2>/dev/null || echo "0")
          
          echo "### 📊 Bundle Size Comparison"
          echo ""
          echo "| Metric | Size |"
          echo "|--------|------|"
          echo "| Base (${{ github.base_ref }}) | ${BASE_SIZE_KB} KB |"
          echo "| Current (PR) | ${CURRENT_SIZE} KB |"
          echo "| **Difference** | **${DIFF} KB** |"
          echo "| **Change** | **${PERCENT}%** |"
          echo ""
          
          if [ $DIFF -lt 0 ]; then
            echo "✅ **Bundle size decreased by $((-DIFF)) KB!** 🎉"
            echo "comparison_status=improvement" >> $GITHUB_OUTPUT
          elif [ $DIFF -eq 0 ]; then
            echo "✅ **No change in bundle size**"
            echo "comparison_status=unchanged" >> $GITHUB_OUTPUT
          else
            echo "⚠️  **Bundle size increased by ${DIFF} KB (+${PERCENT}%)**"
            echo "comparison_status=increase" >> $GITHUB_OUTPUT
            
            # Fail if increase is too large
            if (( $(echo "$PERCENT > 5" | bc -l) )); then
              echo "❌ **Error:** Bundle size increased by more than 5%!"
              exit 1
            fi
          fi
      
      - name: Generate bundle analysis
        run: |
          # Generate detailed bundle analysis if script exists
          if [ -f "scripts/analyze-bundle.js" ]; then
            npm run analyze:bundle || echo "Bundle analysis script not available"
          fi
      
      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis-${{ github.run_id }}
          path: |
            dist/bundle-analysis.html
            current-size.txt
          retention-days: 30
      
      - name: Comment PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const size = fs.readFileSync('current-size.txt', 'utf8').trim();
            
            // Get bundle status from previous step
            const bundleStatus = process.env.BUNDLE_STATUS || 'unknown';
            const comparisonStatus = process.env.COMPARISON_STATUS || 'unknown';
            
            let statusEmoji = '📦';
            if (bundleStatus === 'excellent') statusEmoji = '🏆';
            else if (bundleStatus === 'good') statusEmoji = '✅';
            else if (bundleStatus === 'warning') statusEmoji = '⚠️';
            else if (bundleStatus === 'error') statusEmoji = '❌';
            
            const comment = `### ${statusEmoji} Bundle Size Report
            
            **Current Size:** ${size} KB (gzipped)
            **Target:** 350 KB
            **Stretch Goal:** 300 KB
            
            **Status:** ${bundleStatus.toUpperCase()}
            **Comparison:** ${comparisonStatus.toUpperCase()}
            
            [View detailed bundle analysis](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });