name: 🚀 Simple Deploy to GitHub Pages

on:
  push:
    branches: [main, next]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  NODE_VERSION: '22'

jobs:
  # Build and deploy
  build-and-deploy:
    name: 🏗️ Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: ⚡ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: ⚡ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: ⚡ Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund --silent
      
      - name: ⚡ Build project
        run: |
          echo "🏗️ Building project..."
          npm run build:prod --silent
          echo "✅ Build completed"
      
      - name: ⚡ Verify build
        run: |
          echo "🔍 Verifying build..."
          
          # Check required files
          REQUIRED_FILES=("index.html" "robots.txt" "sitemap.xml")
          for file in "${REQUIRED_FILES[@]}"; do
            if [ -f "dist/$file" ]; then
              echo "✅ $file exists"
            else
              echo "❌ $file missing"
              exit 1
            fi
          done
          
          # Check bundle size
          TOTAL_SIZE=$(find dist -name '*.js' -o -name '*.css' | xargs gzip -c | wc -c)
          TOTAL_SIZE_KB=$((TOTAL_SIZE / 1024))
          echo "📦 Bundle size: ${TOTAL_SIZE_KB} KB"
          
          if [ $TOTAL_SIZE_KB -gt 600 ]; then
            echo "⚠️  Bundle size warning: ${TOTAL_SIZE_KB} KB > 600 KB"
          else
            echo "✅ Bundle size acceptable: ${TOTAL_SIZE_KB} KB"
          fi
      
      - name: ⚡ Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: ⚡ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: ⚡ Verify deployment
        run: |
          echo "🚀 Deployment completed!"
          echo "URL: ${{ steps.deployment.outputs.page_url }}"
          
          # Wait a moment for propagation
          sleep 10
          
          # Quick health check
          if curl -f -s --max-time 15 "${{ steps.deployment.outputs.page_url }}" > /dev/null; then
            echo "✅ Site is accessible"
          else
            echo "⚠️  Site may not be fully propagated yet (this is normal)"
          fi
